### ISSUE TITLE
Support Q => multiple child_processes seem to cause problems

### ISSUE THREAD

**Issue by ORESoftware** [bcoe/nyc#257] opened 2016-05-11 08:16 UTC
this command works

`node index test/some-dir-of-files`

but this doesn't 

`nyc node index test/some-dir-of-files`

however if I do this

`nyc node index test/some-dir-of-files/fileA`

it will work

so my suspicion is that there may be some issue running multiple child processes? Any idea? Let me know if you would like more info, as this is probably not enough to go on.

**Comment by addaleax** [comment] 2016-05-11 08:27
What do you mean by “does not work”? nyc spawns only a single child process in that case, namely `node index test/some-dir-of-files`, so it really should work. What platform are you on, and do you have some kind of reproducible test case?

**Comment by ORESoftware** [comment] 2016-05-11 08:38
I am on OSX, I don't have much more info to give you now, but let me try to dig further to get more clues. By "does not work", I mean that the program execution was not identical. Ideally the program will run exactly the same whether it was run with nyc node or just plain node, in this case, it was not identical at all and I am not sure why yet.

**Comment by bcoe** [comment] 2016-05-14 18:19
1. @ORESoftware what Node and npm version are you on.
2. would it be possible to provide a failing example, or to link us to the project that's failing?

**Comment by cdaringe** [comment] 2016-05-15 00:34
hi all:

i have a failing example to provide.  mine does _not_ use multiple processes, _but_, it does work with `node test/` and it does not work w/ `nyc`.

steps:

1. clone https://github.com/MRN-Code/coinstac-server-core/tree/25fa7f2a5e1491afd04df5c0cad8ff5adb1cd44a
1. npm i, per usual
1. compare output of `npm test` and `npm run brokentest`.  `brokentest` is a nyc run.
  1. you can see that `nyc` simply haults on the [`spawn` call](https://github.com/MRN-Code/coinstac-server-core/blob/25fa7f2a5e1491afd04df5c0cad8ff5adb1cd44a/test/executable.js#L24) while `node test/` has no issue with it.

hopefully that can provide some value!

thanks! v/r,

chris

**Comment by cdaringe** [comment] 2016-05-15 00:37
oh, and `5.11.0` and `2.15.4`.  yea, running npm2 w/ node5...

**Comment by novemberborn** [comment] 2016-05-15 14:22
@cdaringe FWIW, Node.js 6.1.0 and npm 3.9.0, both work fine (well the test fail, but they fail for both). On OSX.

Could you check which nyc version is *actually* installed? (See `node_modules/nyc/package.json`).

**Comment by cdaringe** [comment] 2016-05-15 14:48
PouchDB is not 6.x compatible, so I don't expect the tests to pass there
:/. My installed version matches the package.json.

Thanks for the response!

**Comment by novemberborn** [comment] 2016-05-15 14:51
Switched to 5.1.0 and npm 3.8.7 and rebuilt the previously installed packages. Test run (and fail) with and without nyc.

**Comment by cdaringe** [comment] 2016-05-15 15:18
here's the expected workflow:

![install-process mov](https://cloud.githubusercontent.com/assets/1003261/15275015/e5752c62-1a7d-11e6-9dfd-d2c511d93fb2.gif)

**Comment by cdaringe** [comment] 2016-05-16 02:02
if it's of any help, I do know that my processes are very slow to kill network connections.  pouchdb doesn't kill sockets very well, so sometimes it takes a few seconds for the process to exit.  it _does_ exit eventually always, and within a couple seconds.  i'd be hard pressed to think `nyc` even bothers with any of that stuff, but just trying to think of ideas! :)

**Comment by bcoe** [comment] 2016-05-30 01:56
@cdaringe the problem seems to be this test:

```js
    child.stdout.on('data', data => {
      t.ok(
        data.toString().toLowerCase().indexOf('starting server') !== -1,
        'has startup message'
      );
      child.kill();
    });
```

This test checks for the message `starting server` but when you set log-level to `warn` this message does not output since it is an `info` level message. Tests run fine, as an example, if I change `brokentest` to this:

`"brokentest": "export COINSTAC_SERVER_LOG_LEVEL=silly`

Let me know if this doesn't do the trick for you, and we can open another issue.

**Comment by bcoe** [comment] 2016-05-30 01:57
@ORESoftware I'm going to go ahead and close this issue as solved; please feel free to re-open another issue with an example of a failing project 👍

**Closed by bcoe** 2016-05-30 01:57 UTC

**Comment by cdaringe** [comment] 2016-05-30 02:06
@bcoe, gah.  deep, painful embarrassment!  thanks so much for your time.  i'm super grateful.  i'm glad this was all a non-issue!

**Comment by bcoe** [comment] 2016-05-30 02:07
@cdaringe nothing to be embarrassed about we've all been there! I really appreciate that you provided a reproduction case, and don't hesitate to open more issues in the future.
