### ISSUE TITLE
No coverage files found for Node v5.8.0 and NPM v3.7.3

### ISSUE THREAD

**Issue by arrowrowe** [bcoe/nyc#190] opened 2016-03-11 05:41 UTC
UPDATE: See @addaleax's analysis [here](#issuecomment-203841494).

---

See these Travis logs for details:
- [Using Node v5.8.0 and NPM v3.7.3](https://travis-ci.org/arrowrowe/romi/jobs/115243910) (failed)
- [Using Node v5.8.0 and NPM v3.8.1](https://travis-ci.org/arrowrowe/romi/jobs/115487555) (passed)
- [Using Node v5.7.1](https://travis-ci.org/arrowrowe/romi/jobs/115245095) (passed)
- [Using Node v4.4.0](https://travis-ci.org/arrowrowe/romi/jobs/115243911) (passed)

```
ERROR: No coverage files found.
```

This happens only using Node v5.8.0 and NPM v3.7.3 together.

---

UPDATE: Thanks to @novemberborn's response and @thangngoc89's suggestion in MoOx/statinamic#296, I am working around telling Travis to install latest NPM (i.e. 3.8.1). Below is added to `.travis.yml`.

```yml
before_install:
  - npm install -g npm@latest
```

**Comment by novemberborn** [comment] 2016-03-11 11:04
@arrowrowe I cloned https://github.com/arrowrowe/romi and installed it locally. `npm test` ran fine:

```
-----------|----------|----------|----------|----------|----------------|
File       |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
-----------|----------|----------|----------|----------|----------------|
 romi/     |    94.34 |      100 |      100 |      100 |                |
  index.js |    94.34 |      100 |      100 |      100 |                |
-----------|----------|----------|----------|----------|----------------|
All files  |    94.34 |      100 |      100 |      100 |                |
-----------|----------|----------|----------|----------|----------------|
```

This is on OS X, npm 3.8.1.

Can you reproduce this outside of Travis?

**Comment by sarbbottam** [comment] 2016-03-12 03:07
Works fine for me in `v5.8.0`

**Comment by arrowrowe** [comment] 2016-03-12 06:15
Thanks for responding! I will retry it later to confirm.

**Comment by arrowrowe** [comment] 2016-03-12 06:34
Failed on Ubuntu 14.04.1, using Node v5.8.0 and NPM v3.7.3, as the log below shows. (No need to paste it in fact. It is same with the Travis log.)

```
   3 passed

----------|----------|----------|----------|----------|----------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
----------|----------|----------|----------|----------|----------------|
----------|----------|----------|----------|----------|----------------|
All files |      100 |      100 |      100 |      100 |                |
----------|----------|----------|----------|----------|----------------|

ERROR: No coverage files found.
npm ERR! Test failed.  See above for more details.
```

However, `npm test` **does run fine** after I update to NPM v3.8.1, remove `node_modules` and `npm i` again. So, is this problem happening only using Node v5.8.0 and NPM v3.7.3?........ Or was I making a mistake somewhere?...

Not sure what causes this.........

**Comment by novemberborn** [comment] 2016-03-12 13:34
> So, is this problem happening only using Node v5.8.0 and NPM v3.7.3?........ Or was I making a mistake somewhere?...

If you remove `node_modules` and reinstall under npm 3.7.3, does it work then?

**Comment by arrowrowe** [comment] 2016-03-12 14:39
@novemberborn I suppose not, as Travis's fresh install (Node v5.8.0 and NPM v3.7.3) fails. I am confirming it now. Will update later.

**Comment by thangngoc89** [comment] 2016-03-13 04:42
@arrowrowe woa. Thanks for you efforts. So much trouble with npm.

**Comment by bcoe** [comment] 2016-03-31 04:30
@arrowrowe this is a really interesting bug! I'd be interested to diff npm@3.8.1 vs. npm@3.7.3 -- I wonder if we touched anything in the script execution logic.

**Comment by addaleax** [comment] 2016-03-31 09:21
I think I understand this.

This has nothing to do with npm versions at all. As far as I can tell, it is because the Node.js distributions [have the shebang at the start of npm-cli.js replaced](https://github.com/nodejs/node/blob/33c27f8fcffd7b0c6d609fdd4503b4f7a3c45bcd/tools/install.py#L107-L117) with a (relative) reference to the Node.js executable.
This throws `spawn-wrap` off, though: It relies on being able to tell that Node.js is invoked (e.g. because the command name that should be executed is `node`) or that adding a directory containing a wrapper script to the `PATH` environment variable a will suffice. Since the command name is `npm`, not `node`, and the Node.js interpreter path is hardcoded in the `npm-cli.js`, spawn-wrap cannot attach its handler code anywhere inside the npm process.
This could even be fine, because `PATH` contains the spawn-wrap wrapper, so that one should get executed when a Node.js script is invoked, right? Well, `npm` likes to make its own changes to `PATH`, and sets the directory of the currently running Node.js executable [with a higher priority](https://github.com/npm/npm/blob/master/lib/utils/lifecycle.js#L97-L98) than everything else in `PATH`. So again, no chance for spawn-wrap to attach itself.

Re-installing npm solved the problem because npm’s copy of npm-cli.js contains no modified shebang, so the “right” wrapper script gets invoked. Another workaround might be running something like `nyc node $(which npm) test` or something like that.

(You can see the difference between the installed npm-cli.js files [here](https://travis-ci.org/addaleax/travisci-test/builds/119751406).)

I don’t know whether this is fixable without either some special handing of `npm` commands in spawn-wrap or changes to the npm cli itself.

**Comment by arrowrowe** [comment] 2016-03-31 11:23
Thanks a lot @addaleax! I will leave the right to close this issue to the owner @bcoe.

**Comment by addaleax** [comment] 2016-03-31 17:45
I think I’d be willing to write a patch for spawn-wrap which adds special handling for npm, if there’s a chance it gets landed. @bcoe, what do you think? izs seems to have abandoned that module, but given that you’re a member of npm and tapjs, I imagine you can assess the situation better than I do?

**Comment by bcoe** [comment] 2016-03-31 17:52
@addaleax wonderful find, yes please submit a patch to spawn-wrap and I can help land it.

**Comment by bcoe** [comment] 2016-03-31 17:54
@addaleax if I'm reading this correctly, does the issue arise when the platform is detected as `PORTABLE`?

**Comment by addaleax** [comment] 2016-03-31 18:08
@bcoe The issues arises either way. `PORTABLE` is set for generating the Node.js binary distribution tarballs, and is not set when running their `make install` in a source tree (I have tested this with both configurations). In any case the node binary is invoked using its full path, and that moves `PATH` out of the way.

**Comment by sarbbottam** [comment] 2016-04-02 21:44
There is a work around to this, please refer [this comment](https://github.com/bcoe/nyc/issues/211#issuecomment-204807872) at #211, instead of `npm test`, if the command aliased to `npm test` is used, it works fine.

**Comment by bcoe** [comment] 2016-04-03 04:07
@addaleax what's a good email to use for you, I'd love to get you into our slack so we can debug this issue.

**Comment by addaleax** [comment] 2016-04-03 10:12
@bcoe anna@addaleax.net works fine, but I won’t have much time until the CEST evening :)

**Comment by addaleax** [comment] 2016-04-03 21:32
@bcoe Seen? Would like to delete the comment with my raw email address if that’s okay. :smile:

**Comment by bcoe** [comment] 2016-04-03 22:23
@sarbbottam @arrowrowe @addaleax give this a shot:

`npm i nyc@bundle-test`

It's bundled with a version of `spawn-wrap` that should fix this underlying bug.

**Comment by addaleax** [comment] 2016-04-03 22:35
@bcoe Yup, seems to work

**Comment by sarbbottam** [comment] 2016-04-03 22:41
@bcoe awesome, it saves me from repeating.

**Comment by arrowrowe** [comment] 2016-04-04 00:13
@bcoe :+1:  the fix works for straight-forward scripts like [this](https://travis-ci.org/arrowrowe/romi/jobs/120512370) (`nyc npm run test:only`, with `npm run test:only` equivalent to `ava`), but fails for more complex calling like [this](https://travis-ci.org/arrowrowe/romi/jobs/120511565) (`nyc npm run test:easy`, with `npm run test:easy` equivalent to `npm run lint && npm run test:only` and `npm run test:only` equivalent to `ava`). I will avoid the later complex usage :laughing:

**Comment by jamestalmage** [comment] 2016-04-04 00:35
@arrowrowe 
You almost certainly don't want `npm run lint` being run with coverage, so your first link is the better way to do it. Also, I would avoid using `npm run` for such short commands (loading up `npm` does have some overhead, and your existing commands are really short).

If I were you, `package.json` would look like this:

```js

  "scripts": {
    "lint": "xo",
    "test:only": "ava",
    "test:easy": "xo && ava",
    "test": "xo && nyc ava && nyc check-coverage --statements 100 --lines 100 --functions 100 --branches 100",
    "test:report": "nyc --reporter=lcov ava && google-chrome coverage/lcov-report/index.html"
  },
```

Also, IMO the `lint` and `test:easy` scripts are pretty useless. Both AVA and XO will default to using your local installation. You can install them globally and use them directly from the command line and they will behave appropriately.

```
$ npm install --global ava xo

# These global CLI commands will find and use the local versions of both projects:
$ xo && ava
```

Note that this prefer-local behavior is a feature of AVA and XO. There are other projects that do that, but they have to code it themselves.

**Comment by arrowrowe** [comment] 2016-04-04 01:00
@jamestalmage thanks for the advice! It does benefit shortening scripts. I didn't notice the fact that my tortuous usage put `npm run lint` under coverage as well :(. And making scripts recursively call themselves is no more than a bad personal habit, which I will remember to avoid later on. The global usage of AVA and XO is cool; it is just sometimes there are different test suits across projects, and `npm test` always works. Thanks for your advice again.

**Comment by jamestalmage** [comment] 2016-04-04 01:09
> and `npm test` always works

Indeed, that's a good reason to use it. If you consistently use `test:only` and `test:easy` for all projects in your organization - that is good reason to include those scripts in `package.json` as well. It serves as documentation on the sort of build commands that can be run. I was just pointing out that there are shortcuts which should run a little faster.

**Comment by addaleax** [comment] 2016-04-04 01:24
> And making scripts recursively call themselves is no more than a bad personal habit, which I will remember to avoid later on.

I think it’s quite okay. Either way, the issue with running nyc + recursive npm scripts should be fixed soon, too.

**Comment by jamestalmage** [comment] 2016-04-04 02:46
> I think it’s quite okay. 

Agreed - it's not a mistake to do so, just a bit verbose in this particular case.

**Comment by novemberborn** [comment] 2016-04-04 09:51
> You almost certainly don't want npm run lint being run with coverage

@jamestalmage I doubt this has any adverse effects though. The linter code wouldn't be instrumented and it would use the filesystem to access the code.

**Comment by jamestalmage** [comment] 2016-04-04 20:09
> I doubt this has any adverse effects though.

Wrapping with `spawn-wrap` and `foreground-child` have their cost. The use of `append-transform` has (minimally) adverse affects on require time. The affect should be minimal however.

**Comment by bcoe** [comment] 2016-04-05 05:36
@addaleax @arrowrowe can we close this at this point? If you run:

`npm i nyc@next`

We've landed various fixes to the `5.8.0` bug.

**Comment by arrowrowe** [comment] 2016-04-05 06:26
@bcoe good to me now! :100:

**Comment by MoOx** [comment] 2016-04-05 06:42
Maybe close when you cut a stable release? (This helps people tracking the issue to now when it's "stable").

**Comment by bcoe** [comment] 2016-04-06 16:28
`nyc@6.2.1` is released.

**Closed by bcoe** 2016-04-06 16:28 UTC
