### ISSUE TITLE
Exit with status code 137 on node 4 when using with AVA, --all and --require babel hook

### ISSUE THREAD

**Issue by thangngoc89** [bcoe/nyc#181] opened 2016-03-04 11:36 UTC
I have a [repo](https://github.com/MoOx/statinamic) setup with AVA and nyc

```
nyc --all --require babel-core/register ava
```

AVA option

```
"require": [
   "babel-core/register"
]
```

On node 5, all tests passed.

But on node 4, npm@2 doesn't dedupe `babel-core/register` by default, we will have 2 different versions of `babel-core/register` : one from AVA and one from project's dependencies. 

This will cause test [process exit with status code 137](https://travis-ci.org/MoOx/statinamic/jobs/113613499#L334)

My current solution is disable coverage on node 4.

poke @jamestalmage

**Comment by jamestalmage** [comment] 2016-03-04 11:46
The other issue here relates to the fact that he wanted to use the `--all` option. Which fails on ES6 files if you try to use AVAs `--require`  flag instead of nycs. 

Also, it is preferable to use AVA's `require` pkgConf to provide a cleaner cli experience across both covered and non-covered test runs. Again, that doesn't work for `--all`

**Comment by novemberborn** [comment] 2016-03-04 12:37
It's starting to seem that `--require` here is just a cheat. You should let the child process be responsible for setting up the transpiler. nyc can hook into that better now than when `--require` was introduced. Basically nyc's `--require` is only useful if you have test code you *always* run using nyc and you're too lazy to manage the transpiler yourself.

But… then there's `--all`. I think we're doing that wrong too. We should still find all the files however rather than instrumenting them up front we should just keep track of them. Then once we have the coverage report we can figure out which files were never loaded and synthesize an empty report for those files, based on the raw source.

**Comment by MoOx** [comment] 2016-03-04 21:44
A workaround for --all is to add empty test files that just require the (not yet) tested file?

**Comment by novemberborn** [comment] 2016-03-05 13:25
> A workaround for --all is to add empty test files that just require the (not yet) tested file?

Yea, that way AVA can load the files and you won't need the conflicting `--require` for `nyc`.

Once AVA supports custom Babel configs you could use <https://github.com/novemberborn/babel-plugin-import-glob> to require all source files in one go, so you don't forget any.

Until we fix `--all` here that is :wink:

**Comment by MoOx** [comment] 2016-03-05 14:57
I can already glob with `ava **/__tests__/*.js` :)

**Comment by jamestalmage** [comment] 2016-03-06 04:48
> It's starting to seem that --require here is just a cheat. 

Also, if you are using Node 4+ only (not 0.12 or 0.10), you can use the native `--require` flag:

```
$ node --require babel-register node_modules/.bin/nyc --all ava
```

If you need to support Node `0.12` or below, I have created [`spawn-require`](https://github.com/jamestalmage/spawn-require), which would be used as follows:

```
$ spawn-require babel-register nyc --all ava
```

> But… then there's --all. I think we're doing that wrong too... find all the files ... just keep track of them. ... figure out which files were never loaded and synthesize an empty report

:+1:

**Comment by novemberborn** [comment] 2016-03-06 12:58
Closing this issue since it's by design. Tracking improvements in #183.

**Closed by novemberborn** 2016-03-06 12:58 UTC
