### ISSUE TITLE
Cannot read property 'start' of undefined

### ISSUE THREAD

**Issue by xjamundx** [bcoe/nyc#239] opened 2016-04-27 14:57 UTC
## Reproduction Steps

1. Create an `index.js` file which uses babel-register, destructuring and a binary expression:

```js
require('babel-register')
const {x} = 'hi' || true
```

2. Run `nyc` with html reporter and `ava`:

`./node_modules/.bin/nyc --reporter html ./node_modules/.bin/ava ./index.js `

**Error**
```
/Users/jamuferguson/dev/web/node_modules/nyc/node_modules/istanbul/lib/report/html.js:276
                startCol = meta.start.column;
                               ^

TypeError: Cannot read property 'start' of undefined
    at /Users/jamuferguson/dev/web/node_modules/nyc/node_modules/istanbul/lib/report/html.js:276:32
    at Array.forEach (native)
    at annotateBranches (/Users/jamuferguson/dev/web/node_modules/nyc/node_modules/istanbul/lib/report/html.js:255:30)
    at HtmlReport.Report.mix.writeDetailPage (/Users/jamuferguson/dev/web/node_modules/nyc/node_modules/istanbul/lib/report/html.js:426:9)
    at /Users/jamuferguson/dev/web/node_modules/nyc/node_modules/istanbul/lib/report/html.js:489:26
    at SyncFileWriter.extend.writeFile (/Users/jamuferguson/dev/web/node_modules/nyc/node_modules/istanbul/lib/util/file-writer.js:57:9)
    at FileWriter.extend.writeFile (/Users/jamuferguson/dev/web/node_modules/nyc/node_modules/istanbul/lib/util/file-writer.js:147:23)
    at /Users/jamuferguson/dev/web/node_modules/nyc/node_modules/istanbul/lib/report/html.js:488:24
    at Array.forEach (native)
    at HtmlReport.Report.mix.writeFiles (/Users/jamuferguson/dev/web/node_modules/nyc/node_modules/istanbul/lib/report/html.js:482:23)
```

You can also try this out in my repo here which is hooked up with this problem:
https://github.com/xjamundx/nyc-broke

**Comment by novemberborn** [comment] 2016-04-27 15:42
Looks like corrupted coverage data is being output by nyc, and it's tripping up the HTML reporter. If you could share your code, or even better an isolated reproduction, that would help in tracking this down.

**Comment by xjamundx** [comment] 2016-04-27 15:48
Thanks @novemberborn working on doing just that :)

**Comment by xjamundx** [comment] 2016-04-27 16:44
Okay this is fun.. It was a lot of code, but now we're down to:

**feedback.js**
```
var { weird } = true && {}
```

**feedback.test.js**
```
import test from 'ava'
test('feedback', t => {
	t.truthy(require('./feedback'))
})
```

Also might be good to know that my `ava` config looks like this:
```
  "ava": {
    "babel": "inherit",
    "require": [
      "babel-register"
    ]
  },
```

The other variable appears to be the location of the feedback.js file, which sounds weird, but let me explain. My root is `~/dev/myco/myapp` and feedback.js file was originally in `~/dev/myco/myapp/public/js/calculator/lib/. I can move it up a few directories and it still repros, but if I move it into the root folder (or even in `public`) it doesn't want to reproduce.

I'll keep poking away at this. Are there any directories that might be caching things or where can I look for these

**Comment by xjamundx** [comment] 2016-04-27 16:47
```
~/dev/paypal/p2pnodeweb (junit) $ more .nyc_output/55473.json 
{"/Users/jamuferguson/dev/paypal/p2pnodeweb/public/js/feedback.js":{"path":"/Users/jamuferguson/dev/paypal/p2pnodeweb/public/js/feedback.js","s":{},"b":{"1":[1,1]},"f":{},"fnMap":{},"statementMap":{},"branchMap":{"1":{"line":1,"type":"binary-expr","locations":[{"start":{"line":1,"column":16},"end":{"line":1,"column":23}}]}}}}
```

**Comment by novemberborn** [comment] 2016-04-27 16:58
> I'll keep poking away at this. Any other suggestions or directions I can go to look into this?

That seems pretty minimal. Move it as high up as you can while still reproducing the issue. If you could share a GitHub repo that'd be great.

Coverage is only generated for `feedback.js`? We've had issues with `__tests__` test code being instrumented by nyc, though that should be fixed both here and in AVA.

**Comment by xjamundx** [comment] 2016-04-27 17:01
FYI using node6 (instead of `babel-register` to handle destructuring) makes the issue dissapear

**Comment by xjamundx** [comment] 2016-04-27 17:01
@novemberborn yeah so that's the annoying thing. when i create a fresh directory it won't repro (yet). Still trying to figure out what other variables might exist....

**Comment by novemberborn** [comment] 2016-04-27 17:07
Both AVA and nyc use `node_modules/.cache` for their caches. However, before you go and wipe that directory, perhaps try the following:

1. Copy/paste the entire project folder
1. In *that* copy, `rm -rf node_modules` and reinstall
1. See if that reproduces
1. If not, copy/paste again and `rm -rf node_modules/.caches`, see if that reproduces

If the problem goes away then I'd say this might just be a fluke…

**Comment by xjamundx** [comment] 2016-04-27 17:35
Yeah it's one of those terrible things.

I now have `./public/js/bad.js` and `./test.js` I can repro the error 100% of the time with this command:
`./node_modules/.bin/nyc ./node_modules/.bin/ava ./test.js`

**test.js**
```js
require('babel-register')
require('ava')('feedback', t => {
        t.truthy(require('./public/js/bad'))
})
```

**bad.js**
```js
var { weird } = true && {}
```

**.nyc_output/57463.json**
```json
{"/Users/jamuferguson/dev/paypal/p2pnodeweb/public/js/bad.js":{"path":"/Users/jamuferguson/dev/paypal/p2pnodeweb/public/js/bad.js","s":{},"b":{"1":[1,1]},"f":{},"fnMap":{},"statementMap":{},"branchMap":{"1":{"line":1,"type":"binary-expr","locations":[{"start":{"line":1,"column":16},"end":{"line":1,"column":23}}]}}}}
```

**BUT** 

If I simply do this

1. `cp -r public not-public`
2. update `test.js` to point to `not-public` instead of `public`
3. run the `nyc` command

It will not fail and the `.nyc_output`.

**Comment by xjamundx** [comment] 2016-04-27 17:48
- ❌ `./node_modules/.bin/nyc --reporter lcov ./node_modules/.bin/ava ./test.js`
- ❌ `./node_modules/.bin/nyc --reporter html ./node_modules/.bin/ava ./test.js`
- ✅ `./node_modules/.bin/nyc --reporter lcov ./node_modules/.bin/ava ./test.js`

**Comment by xjamundx** [comment] 2016-04-27 18:05
Even more bazaar:

1. `mv public not-public`
2. update `test.js`  to point to `not-public` instead of `public`
3. run the `nyc` command

not failing, but fails in the original place

**Comment by xjamundx** [comment] 2016-04-27 18:18
Yeah it has to be inside of `public/js` to fail. If I move it to `public` or `public/ghost` it will not fail, but if it's inside `public/js/tent` or `public/js/snooze` it will fail. That's what I'm thinking it's some weird caching thing that ties to the directory name. 

A new repo created from scratch doesn't have any of these issues and it doesn't care about the folder name. Will try nuking my `node_modules` again and seeing if that helps, but now I'm thinking a better approach is to remove cases in my code where I use destructuring AND binary expression

**Comment by novemberborn** [comment] 2016-04-27 19:29
@xjamundx would you mind putting up a GitHub repo with your reproduction? I'll try and reproduce it locally when I get a chance.

**Comment by xjamundx** [comment] 2016-04-27 19:52
@novemberborn still struggling with getting it to work outside of my main repo, but I have a few ideas of how to do it.

**Comment by xjamundx** [comment] 2016-04-27 21:03
@novemberborn my branch now repros the issue with `npm test`:
https://github.com/xjamundx/nyc-broke

**Comment by xjamundx** [comment] 2016-04-27 21:06
Will update the description with reproduction steps

**Comment by bcoe** [comment] 2016-05-01 18:20
@xjamundx thanks for providing a reproduction, I will dig into this early next week if no one else gets to it 👍

**Comment by kentcdodds** [comment] 2016-05-03 21:46
Another test case for you. This code triggered the same issue:

```javascript
function isPhoneNumber(string) {
	return (
		!string.match(/([a-z]|@)/i) && // contains letter or @ symbol
		string.replace(/\D/g, '').length > 5 // has at least 5 numbers
	)
	return !containsLetterOrAtSymbol(string) && hasAtLeastFiveNumbers(string)
}
```

Changing it to this fixed the issue:

```javascript
function isPhoneNumber(string) {
	return !containsLetterOrAtSymbol(string) && hasAtLeastFiveNumbers(string)
}

function containsLetterOrAtSymbol(string) {
	return (/([a-z]|@)/i).test(string)
}

function hasAtLeastFiveNumbers(string) {
	return string.replace(/\D/g, '').length > 5
}
```

**Comment by novemberborn** [comment] 2016-05-09 10:50
@xjamundx playing with the reproduction now. I think Istanbul's HTML reporter is simply failing to produce the report. If I change the scripts to:

```
    "test": "nyc --exclude=index.js ava index.js",
    "posttest": "nyc report --reporter=html"
```

I get 100% coverage in the `test` output:

```
--------------|----------|----------|----------|----------|----------------|
File          |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
--------------|----------|----------|----------|----------|----------------|
 feedback/    |      100 |      100 |      100 |      100 |                |
  feedback.js |      100 |      100 |      100 |      100 |                |
--------------|----------|----------|----------|----------|----------------|
All files     |      100 |      100 |      100 |      100 |                |
--------------|----------|----------|----------|----------|----------------|
```

But the `posttest` fails.

I don't think there's much nyc can do about this. Like @kentcdodds found, sometimes the code needs to be changed for Istanbul to be happy.

(I'm excluding `index.js` since I did spot some weird coverage data for that file, but that's not the reason for the crash.)

**Comment by novemberborn** [comment] 2016-05-09 10:59
I spoke too soon. The HTML report is crashing because there are no statements in the coverage data:

```
{
    "/private/var/folders/_6/p8qxp_3n62zg9081tvb0lcc80000gn/T/tmp.wI9zPQGl/nyc-broke/public/js/feedback/feedback.js": {
        "path": "/private/var/folders/_6/p8qxp_3n62zg9081tvb0lcc80000gn/T/tmp.wI9zPQGl/nyc-broke/public/js/feedback/feedback.js",
        "s": {},
        "b": {
            "1": [1, 1]
        },
        "f": {},
        "fnMap": {},
        "statementMap": {},
        "branchMap": {
            "1": {
                "line": 1,
                "type": "binary-expr",
                "locations": [{
                    "start": {
                        "line": 1,
                        "column": 12
                    },
                    "end": {
                        "line": 1,
                        "column": 19
                    }
                }]
            }
        }
    }
}
```

Here I changed the `feedback.js` file to `var { a } = true && {}`.

If I run this with Node 6 and disable `babel-register` I get this data:

```
{
    "/private/var/folders/_6/p8qxp_3n62zg9081tvb0lcc80000gn/T/tmp.wI9zPQGl/nyc-broke/public/js/feedback/feedback.js": {
        "path": "/private/var/folders/_6/p8qxp_3n62zg9081tvb0lcc80000gn/T/tmp.wI9zPQGl/nyc-broke/public/js/feedback/feedback.js",
        "s": {
            "1": 1
        },
        "b": {
            "1": [1, 1]
        },
        "f": {},
        "fnMap": {},
        "statementMap": {
            "1": {
                "start": {
                    "line": 1,
                    "column": 0
                },
                "end": {
                    "line": 1,
                    "column": 22
                }
            }
        },
        "branchMap": {
            "1": {
                "line": 1,
                "type": "binary-expr",
                "locations": [{
                    "start": {
                        "line": 1,
                        "column": 12
                    },
                    "end": {
                        "line": 1,
                        "column": 16
                    }
                }, {
                    "start": {
                        "line": 1,
                        "column": 20
                    },
                    "end": {
                        "line": 1,
                        "column": 22
                    }
                }]
            }
        }
    }
}
```

`babel-register` emits ES5 code, coverage for which is mapped back to the original source through source maps. It looks like we're able to map the `true && {}` branch but not the full `var { a } =` statement. 

I don't think we can do much about the source mapping, though perhaps we can check whether the report contains statements for all branches. The HTML report won't be entirely accurate but at least it won't crash. @bcoe?

**Comment by acao** [comment] 2016-05-11 15:51
I came up with a temporary workaround for this issue, appplicable to those who are seeking a text-based lcov.info output for usage with tools such as https://atom.io/packages/lcov-info, etc.

I wanted to use --reporter=lcov, however this wants to write to html as well as the lcov.info. All I needed was the lcov.info for my purposes.

First,in npm test as specified above, run nyc with your test harness without specifying --reporter. The default reporter works for me at least, which is nice for the visual stdout.

Then, use this script for ``npm postttest``

```
"posttest": "mkdirp ./coverage && $(npm bin)/nyc report --reporter=text-lcov >> coverage/lcov.info",
```
:ok:

**Comment by bcoe** [comment] 2016-05-14 18:46
@novemberborn #255 should address this problem, once it goes out the door?

**Comment by novemberborn** [comment] 2016-05-15 14:09
@bcoe no. The problem here is that the branch map refers to statements that have been removed from the coverage because they could not be mapped to the original source.

I'm proposing we remove branches that refer to missing statements. It makes the reports less accurate, which can't be helped, but at least it won't crash.

**Comment by spudly** [comment] 2016-05-18 17:31
I get this error when testing a function with a `switch` statement and a comment after a `case` that falls through. See below:

```js
const bacon = method => {
  switch (method) {
    case 'boiled':
      return 'yuck';
    case 'baked': // Fall Through
    default:
      return 'yum';
  }
};
```

If I remove the comment, it works correctly.

**Comment by bcoe** [comment] 2016-06-04 19:28
@xjamundx closing in favor of https://github.com/bcoe/nyc/pull/266

**Closed by bcoe** 2016-06-04 19:28 UTC
Labels: bug

**Comment by bcoe** [comment] 2016-06-15 05:14
@xjamundx give this a spin:

https://github.com/bcoe/nyc#use-babel-plugin__coverage__-for-better-es6es7-support

we've released better support for ES6/ES7 coverage using the __coverage__ instrumentation library.

**Comment by kentcdodds** [comment] 2016-06-15 10:48
I'm definitely a fan of `__coverage__`. Are you aware that currently it didn't support the `/* ignore next */` pragma? So I'm thinking that's technically be a breaking change. Though there's [a pull request](https://github.com/dtinth/babel-plugin-__coverage__/pull/32) to add it.
