### ISSUE TITLE
Why the package name is `nyc`

### ISSUE THREAD

**Issue by sarbbottam** [bcoe/nyc#208] opened 2016-03-29 00:13 UTC
Wondering if it's an abbreviation, what does `nyc` mean?

**Comment by novemberborn** [comment] 2016-03-29 09:46
I imagine it stands for New York City, just like the Istanbul code coverage tool is named after the Turkish city.

**Comment by jamestalmage** [comment] 2016-03-29 14:54
https://youtu.be/fIBRw0dSu34

**Comment by jamestalmage** [comment] 2016-03-29 14:58
Closing as this is nobody's business but the Turks.

**Closed by jamestalmage** 2016-03-29 14:58 UTC

**Comment by jeffijoe** [comment] 2016-08-24 18:49
@novemberborn that's what I am thinking, too - but **Nail Your Coverage** could work, too.

**Comment by viztastic** [comment] 2017-10-06 10:52
'Now You're Covered'

**Comment by kushalmahajan** [comment] 2018-12-27 10:52
What's the official answer then? Just curious! 
Random or something related to history?

**Comment by bcoe** [comment] 2018-12-29 16:45
@kushalmahajan nyc was designed to be a tool that extended on the functionality of Istanbul; introducing support for subprocesses, and a zero-configuration approach to coverage. I called it nyc for two reasons:

1. as a joke, because in the They Might Be Giants song Istanbul Not Constantinople, they mention Istanbul, Constantinople, new Amsterdam, and New York City inn conjunction.
2. because I wanted a short name, so that folks could add it to existing test scripts: `mocha` becomes `nyc mocha`.

**Comment by cgm42** [comment] 2021-10-06 05:11
On that matter, does anyone know why it's called istanbul?

**Comment by sarbbottam** [comment] 2021-10-06 05:19
> On that matter, does anyone know why it's called istanbul?

@cgm42 https://github.com/gotwarlost/istanbul#why-the-funky-name
